// <auto-generated />
using System;
using ECommerceWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceWebApp.Data.Migrations
{
    [DbContext(typeof(ProductsDBContext))]
    partial class ProductsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ECommerceWebApp.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdString")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Product",
                            Description = "Description of product 1",
                            IdString = "0000001",
                            Name = "Product 1",
                            Price = 1.11m,
                            Quantity = 1,
                            imageUrl = "https://web.dev/easy-high-dpi-images/"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Product",
                            Description = "Description of product 2",
                            IdString = "0000002",
                            Name = "Product 2",
                            Price = 2.22m,
                            Quantity = 1,
                            imageUrl = "https://web.dev/easy-high-dpi-images/"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Product",
                            Description = "Description of product 3",
                            IdString = "0000003",
                            Name = "Product 3",
                            Price = 3.33m,
                            Quantity = 1,
                            imageUrl = "https://web.dev/easy-high-dpi-images/"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Product",
                            Description = "Description of product 4",
                            IdString = "0000004",
                            Name = "Product 4",
                            Price = 4.44m,
                            Quantity = 1,
                            imageUrl = "https://web.dev/easy-high-dpi-images/"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Product",
                            Description = "Description of product 5",
                            IdString = "0000005",
                            Name = "Product 5",
                            Price = 5.55m,
                            Quantity = 1,
                            imageUrl = "https://web.dev/easy-high-dpi-images/"
                        });
                });

            modelBuilder.Entity("ECommerceWebApp.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartSave")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
